name: simple_mastodon_updates
description: Mastodon parser for flutter_simple_updates.
version: 0.0.5
homepage: https://github.com/flutter/simple_mastodon_updates
repository: https://github.com/flutter/simple_mastodon_updates
issue_tracker: https://github.com/flutter/simple_mastodon_updates/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  rss_dart: ^1.0.4
  flutter:
    sdk: flutter
  flutter_simple_updates: ^0.1.2
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  nock: ^1.2.3